#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v27
# autospec commit: 65cf152
#
Name     : R-cubature
Version  : 2.1.4
Release  : 60
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/cubature_2.1.4.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/cubature_2.1.4.tar.gz
Summary  : Adaptive Multivariate Integration over Hypercubes
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: R-cubature-lib = %{version}-%{release}
Requires: R-cubature-license = %{version}-%{release}
Requires: R-Rcpp
BuildRequires : R-Rcpp
BuildRequires : buildreq-R
BuildRequires : qtbase-dev

%description
G. Johnson for adaptive multivariate integration over hypercubes
    and the Cuba C library of Thomas Hahn for deterministic and
    Monte Carlo integration. Scalar and vector interfaces for 
    cubature and Cuba routines are provided; the vector interfaces
    are highly recommended as demonstrated in the package
    vignette.

%package dev
Summary: dev components for the R-cubature package.
Group: Development
Requires: R-cubature-lib = %{version}-%{release}
Provides: R-cubature-devel = %{version}-%{release}
Requires: R-cubature = %{version}-%{release}

%description dev
dev components for the R-cubature package.


%package lib
Summary: lib components for the R-cubature package.
Group: Libraries
Requires: R-cubature-license = %{version}-%{release}

%description lib
lib components for the R-cubature package.


%package license
Summary: license components for the R-cubature package.
Group: Default

%description license
license components for the R-cubature package.


%prep
%setup -q -n cubature
pushd ..
cp -a cubature buildavx2
popd
pushd ..
cp -a cubature buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1748896509

%install
export SOURCE_DATE_EPOCH=1748896509
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-cubature
cp %{_builddir}/cubature/src/Cuba/COPYING %{buildroot}/usr/share/package-licenses/R-cubature/f45ee1c765646813b442ca58de72e20a64a7ddba || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/cubature/DESCRIPTION
/usr/lib64/R/library/cubature/INDEX
/usr/lib64/R/library/cubature/Meta/Rd.rds
/usr/lib64/R/library/cubature/Meta/features.rds
/usr/lib64/R/library/cubature/Meta/hsearch.rds
/usr/lib64/R/library/cubature/Meta/links.rds
/usr/lib64/R/library/cubature/Meta/nsInfo.rds
/usr/lib64/R/library/cubature/Meta/package.rds
/usr/lib64/R/library/cubature/Meta/vignette.rds
/usr/lib64/R/library/cubature/NAMESPACE
/usr/lib64/R/library/cubature/NEWS.md
/usr/lib64/R/library/cubature/R/cubature
/usr/lib64/R/library/cubature/R/cubature.rdb
/usr/lib64/R/library/cubature/R/cubature.rdx
/usr/lib64/R/library/cubature/doc/cubature.R
/usr/lib64/R/library/cubature/doc/cubature.Rmd
/usr/lib64/R/library/cubature/doc/cubature.html
/usr/lib64/R/library/cubature/doc/index.html
/usr/lib64/R/library/cubature/doc/version2.R
/usr/lib64/R/library/cubature/doc/version2.Rmd
/usr/lib64/R/library/cubature/doc/version2.html
/usr/lib64/R/library/cubature/help/AnIndex
/usr/lib64/R/library/cubature/help/aliases.rds
/usr/lib64/R/library/cubature/help/cubature.rdb
/usr/lib64/R/library/cubature/help/cubature.rdx
/usr/lib64/R/library/cubature/help/paths.rds
/usr/lib64/R/library/cubature/html/00Index.html
/usr/lib64/R/library/cubature/html/R.css
/usr/lib64/R/library/cubature/tests/testthat.R
/usr/lib64/R/library/cubature/tests/testthat/test_cuba.R
/usr/lib64/R/library/cubature/tests/testthat/test_cubature.R

%files dev
%defattr(-,root,root,-)
/usr/lib64/R/library/cubature/include/cuba.h
/usr/lib64/R/library/cubature/include/cubature.h
/usr/lib64/R/library/cubature/include/exp_cubature.h
/usr/lib64/R/library/cubature/include/exp_cubature_typedefs.h
/usr/lib64/R/library/cubature/include/rcubature.h

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/cubature/libs/cubature.so
/V4/usr/lib64/R/library/cubature/libs/cubature.so
/usr/lib64/R/library/cubature/libs/cubature.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-cubature/f45ee1c765646813b442ca58de72e20a64a7ddba
